# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewWords',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('new_word', models.CharField(max_length=200)),
                ('counts', models.IntegerField()),
                ('types', models.CharField(max_length=200)),
            ],
        ),
    ]
