# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_List',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('new_word', models.CharField(max_length=200)),
                ('counts', models.IntegerField()),
                ('types', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stop_List',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('new_word', models.CharField(max_length=200)),
                ('counts', models.IntegerField()),
                ('types', models.CharField(max_length=200)),
            ],
        ),
    ]
