# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0002_new_list_stop_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop_list',
            old_name='new_word',
            new_name='stop_word',
        ),
    ]
