# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0003_auto_20180418_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_list',
            name='id',
            field=models.IntegerField(db_column='FId', primary_key=True, serialize=False),
        ),
    ]
