# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0006_auto_20180418_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='newwords',
            name='add_new_msg',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newwords',
            name='add_stop_msg',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
