# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0007_auto_20180418_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newwords',
            old_name='add_new_msg',
            new_name='add_msg',
        ),
        migrations.RemoveField(
            model_name='newwords',
            name='add_stop_msg',
        ),
    ]
