# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0008_auto_20180418_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_list',
            name='add_msg',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stop_list',
            name='add_msg',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
