# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-18 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0010_auto_20180418_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop_list',
            name='counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stop_list',
            name='types',
            field=models.CharField(default='', max_length=200),
        ),
    ]
