# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0012_auto_20180424_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_list',
            name='types',
            field=models.CharField(default='', max_length=200),
        ),
    ]
