# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-24 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0015_auto_20180424_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop_list',
            name='counts',
        ),
        migrations.RemoveField(
            model_name='stop_list',
            name='types',
        ),
    ]
