# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0016_auto_20180424_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ch_No_List',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ch_no_word', models.CharField(max_length=200)),
                ('counts', models.IntegerField()),
                ('types', models.CharField(max_length=200)),
                ('add_msg', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
