# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0019_coverate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverate',
            name='coverate',
            field=models.FloatField(max_length=10),
        ),
    ]
