# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_newwords', '0020_auto_20180509_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30)),
            ],
        ),
    ]
